### ISSUE TITLE
Update pls to newer version of python.

### ISSUE THREAD

**Issue by alustinoff** [0xNanda/Oralyzer#1]
Can't install with python 3.7 and 3.8.

Got the error:
```
ERROR: Could not find a version that satisfies the requirement urllib.parse (from -r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for urllib.parse (from -r requirements.txt (line 3))
```

Or:
`Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/urllib-parse/`

**Comment by 0xNanda** [comment]
What command did you use? urllib.parse works fine with python 3.7 and 3.8 as well.

**Comment by alustinoff** [comment]
I use
`pip3 install -r requirements.txt `
and
`python3 -m pip install -r requirements.txt `

Hmm, seems like deal is in absence some packets on my OS

**Comment by 0xNanda** [comment]
If you're still not able to run Oralyzer, then having a look at Issue #3 might help you!
