### ISSUE TITLE
Unable to pass pre-fetched wayback result file

### ISSUE THREAD

**Issue by parag85** [0xNanda/Oralyzer#2]
I have pre-fetched urls.txt file from waybackurls for one domain, whey I am passing this urls.txt, it is not giving result.

It is just printing first URL of urls.txt file.

![image](https://user-images.githubusercontent.com/8840359/88762285-82e79e00-d18e-11ea-91ac-e3ac01e1a2d1.png)

**Comment by 0xNanda** [comment]
`index.cfm?dsp=step_1`  change it to `index.cfm?dsp=`

The parameter value have to omitted, that means you have to delete everything that comes after `=`.

Don't worry, after the coming Update, you won't have to do that manually.

Thanks for using Oralyzer <3
