### ISSUE TITLE
NOT ABLE TO INSTALL!

### ISSUE THREAD

**Issue by ivasugarg** [0xNanda/Oralyzer#3]
Requirement already satisfied: requests in /home/marcmx/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2.20.0)
Collecting bs4
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
ERROR: Could not find a version that satisfies the requirement urllib.parse (from -r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for urllib.parse (from -r requirements.txt (line 3))

**Comment by 0xNanda** [comment]
Install `urllib` manually then.

Run These Commands:

- `cd /usr/lib/python3.8`

- `sudo mkdir urllib && cd urllib`

- `sudo wget https://raw.githubusercontent.com/python/cpython/3.3/Lib/urllib/{__init__,error,parse,response,request,robotparser}.py`
