### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by Gaurav-Jadhav** [0xNanda/Oralyzer#5]
python3 oralyzer.py -u https://target --wayback -o res.txt

        Oralyzer {Open Redirection Analyzer}

[•] Getting juicy URLs with waybackurls
Traceback (most recent call last):
  File "oralyzer.py", line 164, in <module>
    get_urls(url, output)
  File "/root/gaurav/Oralyzer/core/wayback.py", line 32, in get_urls
    no_output = subprocess.run(['waybackurls', url], capture_output=True, text=True)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

**Comment by 0xNanda** [comment]
Do you have waybackurls(https://github.com/tomnomnom/waybackurls/) installed and added to path?

**Comment by 0xNanda** [comment]
Would you mind switching to python 3.7?
