### ISSUE TITLE
Add a switch to provide payload.txt path

### ISSUE THREAD

**Issue by 0xgb** [0xNanda/Oralyzer#6]
If I run this tool from some another directory, the tool does not work.

`python3 /<path-to-oralyzer>/Oralyzer/oralyzer.py -f urls.txt`

This probably is happening because of the following code:

` file = open('payloads.txt','r')`

The script is looking into the current directory for payloads.txt.

This can be fixed if you can add a switch to provide the path/directory where payloads.txt reside.

**Comment by 0xNanda** [comment]
Re-clone the repo and verify if the issue is fixed
